### ISSUE TITLE
Set open state to false as no effect on animated modal

### ISSUE THREAD

**Issue by robertedjones** [iiroj/styled-modal#10]
Hi, I've been animating a modal per your examples. However, when trying to close the modal by setting some state and passing it to the open prop, the prop does not seem to update. I've rolled back to v5.5 (pre-hooks version) and it is working as expected so looks like it's an issue with the hooks implementation.  Thanks for the great library!

**Comment by iiroj** [comment]
Hello, sorry about the lack of response! Apparently I haven't been receiving any notifications from GitHub.

**Comment by iiroj** [comment]
I'll check this out. When I migrated to hooks, I mostly made sure my storybook stories kept working.

**Comment by iiroj** [comment]
I released a new version where I fixed issues related to eslint-plugin-react-hooks. Can you re-test if this helped?

**Comment by camerontaylor** [comment]
This issue still seems to remain. The open prop going from true -> false doesn't propagate to `internalOpen`, looking at the Components devtool.

**Comment by iiroj** [comment]
@camerontaylor sorry about that! I don't really use this myself anymore, so I can only rely on bug reports. I'll check it out.

**Comment by iiroj** [comment]
Hello again. Looking at the hooks implementation it's pretty clear that I've essentially skipped implementing an effect that runs the close handlers and toggles the `internalOpen` state, when the open prop changes without the click handlers.

I'll see if I can get this fixed soon.

I should really add some more tests, but unfortunately don't have the time. I appreciate the reports, though!

**Comment by iiroj** [comment]
@camerontaylor and @robertedjones I've now released version `7.1.3` which hopefully definitely fixes this! I still didn't add new tests, but added manual buttons to the storybook stories to control the external `open` prop, and was able to then verify closing should now work in all the cases:
- when pressing ESC
- when clicking outside the modal
- when toggling the external `open` prop

**Comment by camerontaylor** [comment]
Wow! Thanks @iiroj! It was a pleasant surprised to see `styled-modal                      ^7.1.2  →    ^7.1.3` pop in node-check-updates. That'll really help getting closing animations playing nicely.

**Comment by iiroj** [comment]
Thanks, and sorry about the breakage.
